/** The 10-recipe seed catalog, ported verbatim from the prototype buildSeed(). */
export interface SeedRecipe {
  title: string;
  cuisine: string;
  mins: number;
  time: string;
  difficulty: 'Beginner' | 'Comfortable' | 'Adventurous';
  rating: number;
  reviews: number;
  desc: string;
  tags: string[];
  source?: string;
  nutrition: { cal: number; protein: number; carbs: number; fat: number };
  ingredients: string[];
  steps: string[];
}
const N = (cal: number, protein: number, carbs: number, fat: number) => ({ cal, protein, carbs, fat });

export const SEED_RECIPES: SeedRecipe[] = [
  { title: 'Braised Short Rib Ragu', cuisine: 'Italian', mins: 150, time: '2½ hr', difficulty: 'Adventurous', rating: 4.9, reviews: 312, desc: 'Fall-apart short ribs slow-braised in tomato, red wine and rosemary, folded through pappardelle.', tags: ['comfort', 'weekend', 'pasta'], nutrition: N(680, 42, 55, 28), ingredients: ['2 lb bone-in short ribs', '1 onion, diced', '3 garlic cloves, minced', '2 tbsp tomato paste', '1 cup red wine', '28 oz crushed tomatoes', '2 sprigs rosemary', '12 oz pappardelle', 'Parmesan, to serve'], steps: ['Season ribs generously; sear hard in olive oil until deeply browned on all sides. Remove.', 'Soften onion and garlic in the same pot; stir in tomato paste and cook 2 minutes.', 'Deglaze with wine, scraping the fond; reduce by half.', 'Return ribs with tomatoes and rosemary. Cover and braise at 325°F for 2½ hours until falling apart.', 'Shred meat into the sauce; season. Toss with cooked pappardelle and finish with parmesan.'] },
  { title: 'Khao Soi Chicken Curry', cuisine: 'Thai', mins: 45, time: '45 min', difficulty: 'Comfortable', rating: 4.8, reviews: 198, desc: 'Northern Thai coconut curry noodles with braised chicken, crispy noodle crown and pickled mustard greens.', tags: ['noodles', 'spicy', 'one-pot'], nutrition: N(590, 34, 52, 27), ingredients: ['4 chicken thighs', '3 tbsp khao soi or red curry paste', '2 cans coconut milk', '2 tsp curry powder', '1 tbsp fish sauce', '1 tsp palm sugar', '12 oz egg noodles', 'Shallots, lime, chili oil to garnish'], steps: ['Fry curry paste and curry powder in thick coconut cream until fragrant and split.', 'Add chicken; coat in the paste, then pour in remaining coconut milk. Simmer 25 minutes.', 'Season with fish sauce and palm sugar.', 'Boil noodles; fry a handful until crisp for topping.', 'Bowl the noodles, ladle over curry and chicken; crown with crispy noodles, shallots, lime and chili oil.'] },
  { title: 'Charred Miso Salmon with Blistered Snap Peas', cuisine: 'Japanese', mins: 30, time: '30 min', difficulty: 'Comfortable', rating: 4.9, reviews: 154, desc: 'Sweet-savory miso glaze under a hot broiler, with snap peas charred in the same pan.', tags: ['weeknight', 'high protein', 'seafood'], nutrition: N(470, 38, 22, 24), ingredients: ['4 salmon fillets', '3 tbsp white miso', '1 tbsp mirin', '1 tbsp maple syrup', '2 tsp soy sauce', '12 oz sugar snap peas', '1 tbsp sesame oil', 'Toasted sesame + scallions'], steps: ['Whisk miso, mirin, maple and soy into a glaze; coat salmon and rest 10 minutes.', 'Broil salmon on high 6–8 minutes until charred at the edges and just cooked through.', 'Meanwhile blister snap peas in screaming-hot sesame oil, 2–3 minutes.', 'Plate over rice; scatter sesame and scallions.'] },
  { title: 'Brown Butter Miso Cookies', cuisine: 'Baking', mins: 35, time: '35 min', difficulty: 'Beginner', rating: 5.0, reviews: 86, desc: 'Chewy-centered cookies with nutty brown butter and a savory whisper of miso.', tags: ['dessert', 'cookies', 'make ahead'], nutrition: N(210, 3, 26, 11), ingredients: ['1 cup butter, browned', '2 tbsp white miso', '1 cup brown sugar', '½ cup sugar', '2 eggs', '2¼ cups flour', '1 tsp baking soda', 'Flaky salt'], steps: ['Brown the butter until nutty; cool slightly, then whisk in miso and sugars.', 'Beat in eggs, then fold in flour and baking soda.', 'Chill dough 30 minutes; scoop onto trays.', 'Bake at 350°F for 11–12 minutes until edges set. Finish with flaky salt.'] },
  { title: 'Chicken Tinga Tacos', cuisine: 'Mexican', mins: 40, time: '40 min', difficulty: 'Beginner', rating: 4.7, reviews: 241, desc: 'Smoky chipotle-tomato shredded chicken piled onto charred tortillas with quick-pickled onion.', tags: ['weeknight', 'tacos', 'meal prep'], nutrition: N(430, 33, 38, 16), ingredients: ['1½ lb chicken thighs', '1 onion, sliced', '2 chipotles in adobo', '14 oz fire-roasted tomatoes', '2 garlic cloves', '1 tsp oregano', 'Corn tortillas', 'Pickled red onion, cilantro, cotija'], steps: ['Simmer chicken in salted water 20 minutes; shred.', 'Blend tomatoes, chipotles, garlic and oregano into a smooth sauce.', 'Fry sliced onion; pour in sauce and simmer 5 minutes, then fold in chicken.', 'Char tortillas over flame; pile with tinga, pickled onion, cilantro and cotija.'] },
  { title: 'Summer Peach & Burrata Salad', cuisine: 'Italian', mins: 15, time: '15 min', difficulty: 'Beginner', rating: 4.8, reviews: 122, desc: 'Ripe peaches, torn burrata, basil and hot honey over grilled bread.', tags: ['summer', 'no-cook', 'salad'], source: 'halfbakedharvest.com', nutrition: N(380, 14, 34, 21), ingredients: ['3 ripe peaches, sliced', '8 oz burrata', 'Basil leaves', '2 tbsp hot honey', 'Olive oil + flaky salt', '4 slices sourdough, grilled', 'Aged balsamic'], steps: ['Grill bread until charred; rub with olive oil.', 'Arrange peaches and torn burrata over a platter.', 'Drizzle hot honey, olive oil and balsamic; shower with basil and flaky salt.', 'Serve with the grilled bread for scooping.'] },
  { title: 'One-Pot Lemon Orzo with Shrimp', cuisine: 'Mediterranean', mins: 30, time: '30 min', difficulty: 'Beginner', rating: 4.7, reviews: 178, desc: 'Creamy lemon orzo cooked risotto-style with garlicky shrimp and feta, all in one pan.', tags: ['one-pot', 'weeknight', 'seafood'], source: 'pinchofyum.com', nutrition: N(520, 35, 48, 19), ingredients: ['1 lb shrimp, peeled', '1½ cups orzo', '3 garlic cloves', '3 cups chicken broth', '1 lemon, zest + juice', '½ cup feta', '2 handfuls spinach', 'Dill, to finish'], steps: ['Sear shrimp with garlic 2 minutes per side; remove.', 'Toast orzo in the same pan; add broth gradually, stirring until creamy, ~12 minutes.', 'Stir in lemon, spinach and feta until wilted and glossy.', 'Return shrimp; finish with dill and black pepper.'] },
  { title: 'Cinnamon Roll Focaccia', cuisine: 'Baking', mins: 90, time: '1½ hr', difficulty: 'Comfortable', rating: 4.9, reviews: 64, desc: 'Pillowy overnight focaccia swirled with cinnamon butter and a vanilla glaze.', tags: ['brunch', 'bread', 'weekend'], source: 'sallysbakingaddiction.com', nutrition: N(340, 6, 52, 12), ingredients: ['4 cups bread flour', '2 tsp instant yeast', '1¾ cups warm water', '¼ cup olive oil', '⅓ cup butter, soft', '½ cup brown sugar + 2 tbsp cinnamon', '1 cup powdered sugar + vanilla, for glaze'], steps: ['Mix flour, yeast, water and salt; fold twice, then proof in an oiled pan until bubbly.', 'Dimple with oiled fingers; swirl cinnamon butter across the top.', 'Bake at 425°F for 22–25 minutes until deep gold.', 'Cool slightly and lace with vanilla glaze.'] },
  { title: 'Crispy Rice Bibimbap Bowls', cuisine: 'Korean', mins: 35, time: '35 min', difficulty: 'Comfortable', rating: 4.8, reviews: 141, desc: 'Golden crackly rice, gochujang beef, quick vegetables and a jammy egg.', tags: ['bowls', 'spicy', 'meal prep'], nutrition: N(610, 31, 62, 25), ingredients: ['3 cups cooked short-grain rice', '½ lb ground beef', '3 tbsp gochujang', '1 tbsp soy + 1 tsp sugar', '1 carrot, julienned', '1 cup spinach, blanched', '4 eggs', 'Sesame oil + seeds'], steps: ['Press rice into a hot oiled skillet; crisp undisturbed 6–8 minutes.', 'Brown beef; season with gochujang, soy and sugar.', 'Dress carrot and spinach lightly with sesame oil and salt.', 'Fry eggs jammy. Build bowls over the crispy rice and finish with sesame.'] },
  { title: 'Palak Paneer', cuisine: 'Indian', mins: 40, time: '40 min', difficulty: 'Comfortable', rating: 4.8, reviews: 203, desc: 'Silky spinach gravy with charred paneer, finished with garam masala and cream.', tags: ['vegetarian', 'curry', 'comfort'], nutrition: N(450, 21, 24, 31), ingredients: ['14 oz paneer, cubed', '1 lb spinach, blanched', '1 onion + 2 tomatoes', '1 tbsp ginger-garlic paste', '1 tsp cumin + 1 tsp garam masala', '½ tsp chili powder', '3 tbsp cream'], steps: ['Sear paneer cubes until golden; set aside.', 'Blend blanched spinach smooth.', 'Fry cumin, onion and ginger-garlic; add tomatoes and spices, cook until jammy.', 'Stir in spinach purée; simmer 8 minutes, then fold in paneer and cream.'] },
];
